# Generated by Django 3.2.3 on 2021-05-31 02:53

import cloudinary.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_picture', cloudinary.models.CloudinaryField(default=None, max_length=255, verbose_name='image')),
                ('user_bio', models.TextField()),
                ('user_mail', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=225)),
                ('landing_page', cloudinary.models.CloudinaryField(default=None, max_length=255, verbose_name='image')),
                ('detailed_description', models.TextField()),
                ('link', models.CharField(max_length=225)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.profile')),
            ],
        ),
    ]
